version: "3.7"

services:
  pingtunnelServer:
    image: esrrhs/pingtunnel:latest
    restart: always
    ports:
      - 1080:1080
    command: "./pingtunnel -type client -l 0.0.0.0:1080 -s www.yourserver.com -sock5 1 -key 123456"